### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by hongell** [aerospike/aerospike-collectd#5]
aerospike_plugin.py", line 394
    if any(m == name) for m in metrics):
                        ^
SyntaxError: invalid syntax

python-2.7.5-34.el7.x86_64

**Comment by rguo-aerospike** [comment]
Turns out to be an improper usage of any() anyways

**Comment by hongell** [comment]
Works, thanks.

Aug 31 18:04:37 localhost collectd[54728]: Aerospike Plugin: client 127.0.0.1:3000
Aug 31 18:04:37 localhost collectd[54728]: Aerospike Plugin: Counter({'writes': 172, 'emits': 250})
