### ISSUE TITLE
Can't get read and write reqs counters

### ISSUE THREAD

**Issue by koleo** [aerospike/aerospike-collectd#6]
I am using aerospike-collectd v1.0.3 plugin with Aerospike Server Community Edition v3.9.1.1 (Linux Debian Jessie)

The plugin works well for some counters like `aerospike-service.gauge-client_connections` and some other counters.

But I cannot retrieve the read and write counters for a while: I do not get any value for `aerospike-service.operations-stat_write_reqs` and `aerospike-service.operations-stat_read_reqs`.

These counters used to work a few months ago with an Aerospike v3.8 server but it does not work anymore since an Aerospike server upgrade (I think).

Is it supposed to work on Aerospike 3.9.1.1? Or did I miss something?

**Comment by rguo-aerospike** [comment]
Hi Koleo,

There has been an overhaul of metric names in Aerospike 3.9. You can find out the changes on [this page](http://www.aerospike.com/docs/operations/upgrade/stats_to_3_9).

With regards to the stat_read/write_reqs metrics, those have been [deprecated in 3.9](http://www.aerospike.com/docs/reference/metrics#stat_read_reqs).

The metrics have been broken up based on namespace, and you will find them under each namespace.
eg: instances.aerospike.<hostname>.<namespace>.client_read/write_*

**Comment by koleo** [comment]
You're right, thank you for this information.
